### ISSUE TITLE
Add capability for VASSAR to handle having more than one satellite per orbit

### ISSUE THREAD

**Issue by ani300** [seakers/VASSAR_clean#2]

**Comment by hsbang09** [comment]
@ani300 can you clarify exactly what needs to be done for this? 

My understanding is that the current partitioning + assignment formulation does not allow assigning multiple satellites to the same orbit. Am I wrong?

**Comment by dselva80** [comment]
Not sure if I can reply to this but just to clarify, in the desired
formulation, it should be possible to assign different satellites to the
same orbit.

Best,

Dani

**Comment by ani300** [comment]
I thought so as well

**Comment by hsbang09** [comment]
I thought someone told me that it was not allowed, but I must have been mistaken.

It should be a very simple change so I will implement it now and close this soon!

**Comment by dselva80** [comment]
Hopefully the chromosome and search operators have been designed to allow
this?

Thanks

Dani

**Comment by hsbang09** [comment]
@dselva80 Yes, our current chromosome allows it.

**Comment by hsbang09** [comment]
Antoni and I are moving everything to the new repository: https://github.com/seakers/VASSAR_lib

I made the changes in VASSAR_lib (https://github.com/seakers/VASSAR_lib/commit/76fc5f24d4d4b8f8c4f2740a20d122c6a0b4df95) to allow assigning multiple satellites to the same orbit, so I am closing this.
